# Generated by Django 5.1 on 2024-10-02 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_remove_registration_paper_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="registration",
            old_name="leader_name",
            new_name="name",
        ),
    ]
