# Generated by Django 5.1 on 2024-10-02 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_rename_leader_name_registration_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="registration",
            name="paper_id",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
