# Generated by Django 5.1 on 2024-10-02 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0011_registration_paper_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="registration",
            name="member2_email",
        ),
        migrations.RemoveField(
            model_name="registration",
            name="member2_name",
        ),
        migrations.RemoveField(
            model_name="registration",
            name="member2_non_technical_events",
        ),
        migrations.RemoveField(
            model_name="registration",
            name="member2_phone",
        ),
        migrations.RemoveField(
            model_name="registration",
            name="member2_technical_events",
        ),
        migrations.RemoveField(
            model_name="registration",
            name="member3_email",
        ),
        migrations.RemoveField(
            model_name="registration",
            name="member3_name",
        ),
        migrations.RemoveField(
            model_name="registration",
            name="member3_non_technical_events",
        ),
        migrations.RemoveField(
            model_name="registration",
            name="member3_phone",
        ),
        migrations.RemoveField(
            model_name="registration",
            name="member3_technical_events",
        ),
        migrations.RemoveField(
            model_name="registration",
            name="name",
        ),
        migrations.AlterField(
            model_name="registration",
            name="college",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="registration",
            name="paper_id",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="registration",
            name="team_name",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="registrations",
                to="app.team",
            ),
        ),
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone", models.CharField(blank=True, max_length=15, null=True)),
                (
                    "non_technical_events",
                    models.ManyToManyField(
                        blank=True,
                        related_name="non_technical_registrations",
                        to="app.event",
                    ),
                ),
                (
                    "registration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="app.registration",
                    ),
                ),
                (
                    "technical_events",
                    models.ManyToManyField(
                        blank=True,
                        related_name="technical_registrations",
                        to="app.event",
                    ),
                ),
            ],
        ),
    ]
