# Generated by Django 5.1 on 2024-10-04 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_team_remove_registration_member2_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='team_name',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='non_technical_events',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='registration',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='technical_events',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='paper_id',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='paper_submission_link',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='whatsapp_group_link',
        ),
        migrations.AddField(
            model_name='registration',
            name='member_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='non_technical_events',
            field=models.ManyToManyField(blank=True, related_name='non_technical_registrations', to='app.event'),
        ),
        migrations.AddField(
            model_name='registration',
            name='paper_abstract',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='technical_events',
            field=models.ManyToManyField(blank=True, related_name='technical_registrations', to='app.event'),
        ),
        migrations.DeleteModel(
            name='Team',
        ),
        migrations.DeleteModel(
            name='TeamMember',
        ),
    ]
