# Generated by Django 5.1 on 2024-10-06 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0013_remove_registration_team_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="registration",
            name="food_preference",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Vegetarian", "Vegetarian"),
                    ("Non-Vegetarian", "Non-Vegetarian"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
