# Generated by Django 5.1 on 2024-10-07 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0014_registration_food_preference"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegistrationStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_open", models.BooleanField(default=True)),
            ],
        ),
    ]
