# Generated by Django 5.1 on 2024-10-09 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0015_registrationstatus"),
    ]

    operations = [
        migrations.AddField(
            model_name="registration",
            name="payment_mode",
            field=models.CharField(
                blank=True,
                choices=[("Online", "Online"), ("Offline", "Offline")],
                max_length=10,
                null=True,
            ),
        ),
    ]
