# Generated by Django 5.1 on 2024-10-10 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_registration_payment_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='paid_status',
            field=models.BooleanField(default=False),
        ),
    ]
